default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: admin
  password: scrape-app-db
  host:  scrape-app-db.cdcoi46kmua2.ap-northeast-1.rds.amazonaws.com
  database: scrape

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
